In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('anime.csv')

In [6]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [9]:
#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
#which is the longest running anime

In [35]:
#make a new column for episode count
def ep_no(txt):
    count=False
    data=""
    for i in txt:
        if i==")":
            count=False
            return data
            break     
        if count==True:
            data=data+i
        if i=="(":
            count=True

In [39]:
df["Episodes"]=df['Title'].apply(ep_no)

In [40]:
df["Episodes"]

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: Episodes, dtype: object

In [41]:
#make a new column for time stamp
df.loc[1]

Rank                                                        2
Title       Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                    9.07
Episodes                                               24 eps
Name: 1, dtype: object

In [48]:

def aring_time(txt):
    count=False
    data=""
    for i in range(len(txt)):
        if txt[i]==")":
            for j in range(i+1,i+20):
                data=data+txt[j]

            return data

In [50]:
df["aring_time"]=df["Title"].apply(aring_time)

In [51]:
df["aring_time"]

0     Apr 2009 - Jul 2010
1     Apr 2011 - Sep 2011
2     Oct 2022 - Dec 2022
3     Apr 2015 - Mar 2016
4     Apr 2019 - Jul 2019
5     Apr 2011 - Mar 2012
6     Jan 2021 - Jan 2021
7     Oct 2011 - Sep 2014
8     Apr 2022 - Jun 2022
9     Oct 2012 - Mar 2013
10    Mar 2023 - May 2023
11    Jan 1988 - Mar 1997
12    Jul 2023 - Aug 2023
13    Apr 2021 - Jun 2021
14    Jan 2017 - Mar 2017
15    Apr 2006 - Mar 2010
16    Sep 2016 - Sep 2016
17    Oct 2017 - Mar 2018
18    Oct 2008 - Mar 2009
19    Apr 2008 - Sep 2008
20    Jul 2013 - Jul 2013
21    Sep 2020 - Sep 2020
22    Aug 2017 - Aug 2017
23    Jul 2018 - Oct 2018
24    Apr 2004 - Sep 2005
25    Aug 2016 - Aug 2016
26    Dec 2022 - Dec 2022
27    Oct 2022 - Dec 2022
28    Dec 2022 - Dec 2022
29    Jan 2023 - Jun 2023
30    Jul 2023 - Aug 2023
31    Jan 2018 - Mar 2018
32    Apr 2020 - Oct 2021
33    Jan 2019 - Apr 2019
34    Dec 2020 - Mar 2021
35    Dec 2021 - Feb 2022
36    Jan 2017 - Jan 2017
37    Apr 2023 - Jun 2023
38    Oct 2016 - Dec 2016
39    Jul 2001 - Jul 2001
40    Jul 2013 - Dec 2013
41    Jan 2022 - Apr 2022
42    Oct 2000 - Mar 2002
43    Apr 1998 - Apr 1999
44    Apr 2022 - Oct 2022
45    Jul 2019 - Dec 2019
46    Oct 2014 - Dec 2014
47    Jan 2017 - Mar 2017
48    Oct 2022 - Dec 2022
49    Feb 1999 - Sep 1999
Name: aring_time, dtype: object

In [57]:
#which anime has the highest score
df[df["Score"]==df["Score"].max()]

,Rank,Title,Score,Episodes,aring_time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64 eps,Apr 2009 - Jul 2010

In [60]:
#give me top 5 highest scoring anime
df.sort_values(by="Score" ,ascending=0)
df.head()

,Rank,Title,Score,Episodes,aring_time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64 eps,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24 eps,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13 eps,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51 eps,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10 eps,Apr 2019 - Jul 2019

In [63]:
#which anime has the highest episode count
df['Episodes']=df["Episodes"].str.replace("eps","")
df["Episodes"]=df["Episodes"].astype(int)

In [69]:
df[df["Episodes"]==df["Episodes"].max()]

,Rank,Title,Score,Episodes,aring_time
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010

In [74]:
#animes with top 5 episode count
df=df.sort_values(by="Episodes",ascending=0)

In [75]:
df.head()

,Rank,Title,Score,Episodes,aring_time
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005

In [76]:
#which is the longest running anime
# Split into Start and End dates
df[['Start', 'End']] = df['aring_time'].str.split(' - ', expand=True)

# Convert to datetime
df['Start'] = pd.to_datetime(df['Start'], format='%b %Y')
df['End'] = pd.to_datetime(df['End'], format='%b %Y')

# Calculate duration in days
df['Duration_Days'] = (df['End'] - df['Start']).dt.days

# Convert to years (optional)
df['Duration_Years'] = np.round(df['Duration_Days'] / 365.25, 2)

# Find the longest-running anime
longest = df.loc[df['Duration_Days'].idxmax()]

print(longest[['Title', 'aring_time', 'Duration_Years']])

Title             Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
aring_time                                      Jan 1988 - Mar 1997
Duration_Years                                                 9.16
Name: 11, dtype: object