In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv('countries.csv')

In [3]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [14]:
#Find the shape of the DataFrame.
df.shape

(194, 64)

In [7]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [9]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [ ]:
#Easy
#Print the first 10 rows.
#Print the last 5 rows.
#Find the shape of the DataFrame.
#Display all column names.
#Count the total number of countries.
#Find the number of missing values in each column.
#Display only the country, population, and gdp columns.
#Find the country with the highest population.
#Find the country with the lowest population.
#Sort countries by GDP in descending order.

In [11]:
df.loc[0:9]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
5,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.050000,-61.800000,90.0,...,93763,11.11110,70935,22828,0.00,0.00,Unknown,31.1,Gaston Browne,Prime Minister
6,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.000000,-64.000000,1083820.0,...,46234830,44.74710,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
7,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.000000,45.000000,16760.0,...,2780469,35.51400,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister
8,Australia,Commonwealth of Australia,Australian dollar,Canberra,Australia and New Zealand,Oceania,Australian,-27.000000,133.000000,3557750.0,...,25978935,38.41060,3510274,22468661,4.73,9.09,Full democracy,33.3,Anthony Albanese,Prime Minister
9,Austria,Republic of Austria,Euro,Vienna,Western Europe,Europe,Austrian,47.333333,13.333333,26467.6,...,9042528,40.98360,3684288,5358240,5.10,8.29,Full democracy,39.0,Sebastian Kurz,Federal Chancellor

In [13]:
#Print the last 5 rows.
df.tail()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.2605,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.0000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.0602,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.5660,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [15]:
#Display all column names.
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [18]:
#Count the total number of countries.
df['country'].count()

np.int64(194)

In [23]:
#Find the number of missing values in each column.
df.isna().sum()

country             0
country_long        0
currency            0
capital_city        0
region              0
                   ..
democracy_score     0
democracy_type      0
median_age          0
political_leader    7
title               7
Length: 64, dtype: int64

In [31]:
#Display only the country, population, and gdp columns.
df[['country', 'population', 'gdp']]

                country  population           gdp
0           Afghanistan    41128771  1.458310e+10
1               Albania     2775634  1.888210e+10
2               Algeria    44903225  1.919130e+11
3               Andorra       79824  3.352030e+09
4                Angola    35588987  1.067140e+11
..                  ...         ...           ...
189             Vietnam    98186856  4.088020e+11
190  West Bank and Gaza     5043612  1.911190e+10
191               Yemen    33696614  2.160620e+10
192              Zambia    20017675  2.978450e+10
193            Zimbabwe    16320537  2.067810e+10

[194 rows x 3 columns]

In [49]:
#Find the country with the highest population.
df=df.sort_values(by="population",ascending=0)
print(df.iloc[0])

country                         India
country_long        Republic of India
currency                 Indian rupee
capital_city                New Delhi
region                  Southern Asia
                          ...
democracy_score                  7.23
democracy_type       Flawed democracy
median_age                       23.9
political_leader        Narendra Modi
title                  Prime Minister
Name: 75, Length: 64, dtype: object

In [51]:
#Find the country with the lowest population.
df=df.sort_values(by="population",ascending=1)
print(df.iloc[0])

country                        Tuvalu
country_long                   Tuvalu
currency            Australian dollar
capital_city                 Funafuti
region                      Polynesia
                          ...
democracy_score                   0.0
democracy_type                Unknown
median_age                       21.0
political_leader        Kausea Natano
title                  Prime Minister
Name: 179, Length: 64, dtype: object

In [52]:
#Sort countries by GDP in descending order.
df.sort_values(by="gdp",ascending=0)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.000000,-97.000000,4058100.0,...,333287557,28.70370,56378923,276908634,3.04,7.96,Flawed democracy,33.9,Joe Biden,President
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.000000,105.000000,5285080.0,...,1412175000,24.94120,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
83,Japan,Japan,Japanese yen,Tokyo,Eastern Asia,Asia,Japanese,36.000000,138.000000,43720.0,...,125124989,9.91379,10066305,115058684,2.66,7.99,Flawed democracy,44.7,Yoshihide Suga,Prime Minister
63,Germany,Federal Republic of Germany,Euro,Berlin,Western Europe,Europe,German,51.000000,9.000000,165950.0,...,84079811,34.91850,18793519,65286292,5.36,8.68,Full democracy,40.9,Olaf Scholz,Federal Chancellor
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.000000,77.000000,1790450.0,...,1417173173,14.94460,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Kiribati,Republic of Kiribati,Australian dollar,South Tarawa,Micronesia,Oceania,I-Kiribati,1.416667,173.000000,340.0,...,131232,6.66667,56354,74878,0.00,0.00,Unknown,18.0,Taneti Maamau,President
130,Palau,Republic of Palau,U.S. dollar,Ngerulmud,Micronesia,Oceania,Palauan,7.500000,134.500000,43.0,...,18055,6.25000,3258,14797,0.00,0.00,Unknown,31.7,Thomas Remengesau Jr.,President
119,Nauru,Republic of Nauru,Australian dollar,Yaren,Micronesia,Oceania,Nauruan,-0.533333,166.916667,4.0,...,12668,10.52630,0,12668,0.00,0.00,Unknown,16.3,Lionel Aingimea,President
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.000000,178.000000,18.0,...,11312,6.25000,3900,7412,0.00,0.00,Unknown,21.0,Kausea Natano,Prime Minister
44,Dem. People's Rep. Korea,Democratic People's Republic of Korea,Democratic People's Republic of Korean won,Pyongyang,Eastern Asia,Asia,North Korean,40.000000,127.000000,25900.0,...,26069416,17.61280,9667582,16401834,0.94,1.08,Authoritarian,31.9,Kim Jong-un,Chairman of the Workers Party of Korea

In [ ]:
#Find the top 10 countries with the highest life expectancy.
#Find all countries with a population greater than 100 million.
#Find countries where internet usage is above 90%.
#Calculate the average GDP.
#Calculate the average life expectancy.
#Find the country with the highest CO₂ emissions.
#Find the country with the lowest unemployment rate.
#Count how many countries belong to each continent.
#Find the average life expectancy for each continent.
#Find the average GDP for each continent.

In [53]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [60]:
#Find the top 10 countries with the highest life expectancy.
df=df.sort_values(by='life_expectancy',ascending=0)
df.iloc[0:9]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
165,Switzerland,Switzerland,Swiss franc,Bern,Western Europe,Europe,Swiss,47.000000,8.000000,15042.10,...,8769741,41.50000,2272064,6497677,7.43,9.03,Full democracy,38.1,Simonetta Sommaruga,President
88,Korea,Republic of Korea,Korean won,Seoul,Eastern Asia,Asia,South Korean,37.000000,127.500000,16210.00,...,51628117,18.64410,9588890,42039227,3.14,8.00,Flawed democracy,39.9,Yoon Suk-yeol,President
97,Liechtenstein,Principality of Liechtenstein,Swiss franc,Vaduz,Western Europe,Europe,Liechtensteiner,47.266667,9.533333,53.20,...,39327,28.00000,33610,5717,3.82,0.00,Unknown,39.9,Hereditary Prince Alois,Regent
83,Japan,Japan,Japanese yen,Tokyo,Eastern Asia,Asia,Japanese,36.000000,138.000000,43720.00,...,125124989,9.91379,10066305,115058684,2.66,7.99,Flawed democracy,44.7,Yoshihide Suga,Prime Minister
150,Singapore,Republic of Singapore,Singapore dollar,Singapore,South-Eastern Asia,Asia,Singaporean,1.366667,103.800000,6.60,...,5637022,29.12620,0,5637022,1.52,6.38,Flawed democracy,38.3,Lee Hsien Loong,Prime Minister
99,Luxembourg,Grand Duchy of Luxembourg,Euro,Luxembourg,Western Europe,Europe,Luxembourger,49.750000,6.166667,1321.36,...,650774,33.33330,52836,597938,4.99,8.81,Full democracy,35.0,Xavier Bettel,Prime Minister
105,Malta,Republic of Malta,Euro,Valletta,Southern Europe,Europe,Maltese,35.833333,14.583333,103.80,...,523417,27.84810,26825,496592,2.63,8.21,Full democracy,35.3,Robert Abela,Prime Minister
30,Canada,Canada,Canadian dollar,Ottawa,Northern America,Americas,Canadian,60.000000,-95.000000,577430.00,...,38929902,30.47340,7103929,31825973,4.98,9.15,Full democracy,36.4,Justin Trudeau,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.000000,-18.000000,18720.00,...,381900,47.61900,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister

In [69]:
#Find all countries with a population greater than 100 million.
df[df["population"] > 100000000]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
83,Japan,Japan,Japanese yen,Tokyo,Eastern Asia,Asia,Japanese,36.0,138.0,43720.0,...,125124989,9.91379,10066305,115058684,2.66,7.99,Flawed democracy,44.7,Yoshihide Suga,Prime Minister
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.0,105.0,5285080.0,...,1412175000,24.94120,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.0,-97.0,4058100.0,...,333287557,28.70370,56378923,276908634,3.04,7.96,Flawed democracy,33.9,Joe Biden,President
22,Brazil,Federative Republic of Brazil,Brazilian real,Brasília,South America,Americas,Brazilian,-10.0,-55.0,2368790.0,...,215313498,17.73880,26795765,188517733,2.38,6.97,Flawed democracy,29.2,Jair Bolsonaro,President
12,Bangladesh,People's Republic of Bangladesh,Bangladeshi taka,Dhaka,Southern Asia,Asia,Bangladeshi,24.0,90.0,99010.0,...,171186372,20.85710,103206552,67979820,1.54,5.57,Hybrid regime,22.7,Sheikh Hasina,Prime Minister
51,Egypt,Arab Republic of Egypt,Egyptian pound,Cairo,Northern Africa,Africa,Egyptian,27.0,30.0,39710.0,...,110990103,27.58040,63300985,47689118,1.38,3.36,Authoritarian,20.1,Abdel Fattah el-Sisi,President
109,Mexico,United Mexican States,Mexican peso,Mexico City,Central America,Americas,Mexican,23.0,-102.0,971380.0,...,127504125,50.00000,23843271,103660854,1.67,6.19,Flawed democracy,25.4,Andrés Manuel López Obrador,President
135,Philippines,Republic of the Philippines,Philippine peso,Manila,South-Eastern Asia,Asia,Filipino,13.0,122.0,126750.0,...,115559009,27.33120,60117263,55441746,1.78,6.71,Flawed democracy,20.8,Rodrigo Duterte,President
140,Russia,Russian Federation,Russian ruble,Moscow,Eastern Europe,Europe,Russian,60.0,100.0,2154940.0,...,143555736,16.22220,35708054,107847682,1.55,2.94,Authoritarian,35.0,Vladimir Putin,President
76,Indonesia,Republic of Indonesia,Indonesian rupiah,Jakarta,South-Eastern Asia,Asia,Indonesian,-5.0,120.0,623000.0,...,275501339,21.91300,115892393,159608946,2.13,6.39,Flawed democracy,25.6,Joko Widodo,President
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.94460,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister
129,Pakistan,Islamic Republic of Pakistan,Pakistani rupee,Islamabad,Southern Asia,Asia,Pakistani,30.0,70.0,367230.0,...,235824862,20.46780,146845783,88979079,1.71,4.17,Hybrid regime,16.5,Imran Khan,Prime Minister
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.0,38.0,384761.0,...,123379924,41.48940,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.0,8.0,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President

In [75]:
#Find countries where internet usage is above 90%.
df[df['internet_pct']<90]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
83,Japan,Japan,Japanese yen,Tokyo,Eastern Asia,Asia,Japanese,36.000000,138.000000,43720.0,...,125124989,9.91379,10066305,115058684,2.66,7.99,Flawed democracy,44.7,Yoshihide Suga,Prime Minister
105,Malta,Republic of Malta,Euro,Valletta,Southern Europe,Europe,Maltese,35.833333,14.583333,103.8,...,523417,27.84810,26825,496592,2.63,8.21,Full democracy,35.3,Robert Abela,Prime Minister
81,Italy,Italian Republic,Euro,Rome,Southern Europe,Europe,Italian,42.833333,12.833333,129990.0,...,58856847,32.25000,16681796,42175051,3.13,7.71,Flawed democracy,43.2,Giorgia Meloni,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.000000,15.000000,30055.4,...,10486941,46.41830,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
60,France,French Republic,Euro,Paris,Western Europe,Europe,French,46.000000,2.000000,285538.0,...,67935660,37.26170,12561983,55373677,3.52,7.80,Flawed democracy,37.9,Emmanuel Macron,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.000000,8.000000,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President
32,Chad,Republic of Chad,Central African CFA franc,N'Djamena,Middle Africa,Africa,Chadian,15.000000,19.000000,502380.0,...,17723315,25.88830,13458554,4264761,2.13,1.61,Authoritarian,11.2,Idriss Déby,President
94,Lesotho,Kingdom of Lesotho,Lesotho loti,Maseru,Southern Africa,Africa,Mosotho,-29.500000,28.500000,26000.0,...,2305825,26.44630,1615392,690433,2.63,6.64,Flawed democracy,18.2,Tom Thabane,Prime Minister
143,San Marino,Republic of San Marino,Euro,City of San Marino,Southern Europe,Europe,Sammarinese,43.766667,12.416667,23.0,...,33660,33.33330,763,32897,0.00,0.00,Unknown,42.7,Alessandro Mancini,Captain Regent
112,Monaco,Principality of Monaco,Euro,Monaco,Western Europe,Europe,Monegasque,43.733333,7.400000,NaN,...,36469,33.33330,0,36469,0.00,0.00,Unknown,50.5,Albert II,Sovereign Prince

In [77]:
#Calculate the average GDP.
df['gdp'].agg('mean')

np.float64(514485115126.42487)

In [78]:
#Calculate the average life expectancy.
df['life_expectancy'].mean()

np.float64(71.0)

In [83]:
#Find the country with the highest CO₂ emissions.
df.loc[df['co2_emissions'].idxmax()]

country                                                China
country_long                      People's Republic of China
currency                                        Chinese yuan
capital_city                                         Beijing
region                                          Eastern Asia
                                      ...
democracy_score                                         3.32
democracy_type                                 Authoritarian
median_age                                              34.5
political_leader                                  Xi Jinping
title               General Secretary of the Communist Party
Name: 34, Length: 64, dtype: object

In [86]:
#Find the country with the lowest unemployment rate.
df=df.sort_values(by='unemployment_pct',ascending=0)
df.iloc[0]

country                         South Africa
country_long        Republic of South Africa
currency                  South African rand
capital_city                        Pretoria
region                       Southern Africa
                              ...
democracy_score                         7.24
democracy_type              Flawed democracy
median_age                              23.3
political_leader             Cyril Ramaphosa
title                              President
Name: 155, Length: 64, dtype: object

In [90]:
#Count how many countries belong to each continent.
df['continent'].value_counts()

continent
Africa      54
Asia        47
Europe      44
Americas    35
Oceania     14
Name: count, dtype: int64

In [101]:
#Find the average life expectancy for each continent.
df.groupby('continent')['life_expectancy'].mean()

continent
Africa      62.833333
Americas    72.571429
Asia        73.212766
Europe      78.170732
Oceania     70.142857
Name: life_expectancy, dtype: float64

In [102]:
#Find the average GDP for each continent.
df.groupby('continent')['gdp'].mean()

continent
Africa      5.466804e+10
Americas    9.675583e+11
Asia        7.989775e+11
Europe      5.400586e+11
Oceania     1.402479e+11
Name: gdp, dtype: float64

In [ ]:
#Advanced
#Find the country with the highest renewable energy consumption.
#Find the top 5 countries with the highest democracy score.
#Find all countries where:
#Internet usage > 80%
#Life expectancy > 75
#Unemployment < 5
#Find the country with the highest military expenditure.
#Find the country with the lowest birth rate.
#Find the country with the highest fertility rate.
#Find countries where urban population is greater than rural population.
#Find the top 10 countries with the highest forest area.
#Find the country with the highest health expenditure per capita.
#Find the average health expenditure by continent.

In [103]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [105]:
#Find the country with the highest renewable energy consumption.
df=df.sort_values(by="renewable_energy_consumption_pct",ascending=0)
df.iloc[1]

country                                Somalia
country_long        Somali Democratic Republic
currency                       Somali shilling
capital_city                         Mogadishu
region                          Eastern Africa
                               ...
democracy_score                            0.0
democracy_type                         Unknown
median_age                                11.3
political_leader             Hassan Ali Khayre
title                           Prime Minister
Name: 154, Length: 64, dtype: object

In [107]:
#Find the top 5 countries with the highest democracy score.
df=df.sort_values(by="democracy_score",ascending=0)
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [116]:
#Find all countries where:
#Internet usage > 80%
#Life expectancy > 75
#Unemployment < 5
print(
    df[
        (df['internet_pct'] > 80) &
        (df['life_expectancy'] > 75) &
        (df['unemployment_pct'] < 5)
    ][['country', 'internet_pct', 'life_expectancy', 'unemployment_pct']]
)

                  country  internet_pct  life_expectancy  unemployment_pct
127                Norway       99.0000             83.0             3.171
74                Iceland       99.6870             83.0             3.809
122           New Zealand       95.9102             82.0             3.253
46                Denmark       98.8659             81.0             4.172
79                Ireland       95.1696             82.0             4.362
8               Australia       96.2400             83.0             3.661
165           Switzerland       95.5700             84.0             4.202
121           Netherlands       92.0530             81.0             3.538
99             Luxembourg       98.6600             83.0             4.698
63                Germany       91.4306             81.0             2.989
183        United Kingdom       96.6802             81.0             3.571
9                 Austria       92.5292             81.0             4.707
105                 Malta       87.4698             83.0             2.813
88                  Korea       97.5713             84.0             2.788
83                  Japan       82.9141             84.0             2.641
184         United States       91.7532             76.0             3.611
80                 Israel       90.3000             82.0             3.476
43         Czech Republic       82.6706             77.0             2.370
152              Slovenia       89.0040             81.0             4.180
136                Poland       85.3749             76.0             2.602
150             Singapore       91.0994             83.0             2.758
169              Thailand       85.2700             79.0             0.862
89                 Kuwait       99.7000             79.0             2.482
138                 Qatar      100.0000             79.0             0.095
182  United Arab Emirates      100.0000             79.0             2.754
11                Bahrain      100.0000             79.0             1.399
103              Maldives       85.7606             80.0             4.883

In [118]:
#Find the country with the highest military expenditure.
df=df.sort_values(by="military_expenditure_pct_gdp",ascending=0)
df.iloc[0]

country                      Eritrea
country_long        State of Eritrea
currency              Eritrean nakfa
capital_city                  Asmara
region                Eastern Africa
                          ...
democracy_score                 2.37
democracy_type         Authoritarian
median_age                      14.5
political_leader      Isaias Afwerki
title                      President
Name: 54, Length: 64, dtype: object

In [121]:
print(df.loc[df['military_expenditure_pct_gdp'].idxmax(), 'country'])

Eritrea

In [122]:
#Find the country with the lowest birth rate
print(df.loc[df['birth_rate'].idxmin(), 'country'])

Korea

In [124]:
#Find the country with the highest fertility rate.
print(df.loc[df["fertility_rate"].idxmax(),'country'])

Niger

In [127]:
#Find countries where urban population is greater than rural population.
df[df["rural_population"]<df['urban_population']]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
96,Libya,Socialist People's Libyan Arab Jamahiriya,Libyan dinar,Tripoli,Northern Africa,Africa,Libyan,25.000000,17.000000,153500.0,...,6812341,16.47060,1273772,5538569,1.40,2.19,Authoritarian,22.6,Fayez al-Sarraj,Prime Minister
128,Oman,Sultanate of Oman,Omani rial,Muscat,Western Asia,Asia,Omani,21.000000,57.000000,14589.3,...,4576298,2.32558,560597,4015701,1.80,3.04,Authoritarian,24.9,Haitham bin Tariq,Sultan and Prime Minister
89,Kuwait,State of Kuwait,Kuwaiti dinar,Kuwait City,Western Asia,Asia,Kuwaiti,29.500000,45.750000,1500.0,...,4268873,6.25000,0,4268873,2.31,3.85,Authoritarian,35.1,Sheikh Sabah Al-Ahmad Al-Jaber Al-Sabah,Emir
145,Saudi Arabia,Kingdom of Saudi Arabia,Saudi Arabian riyal,Riyadh,Western Asia,Asia,Saudi Arabian,25.000000,45.000000,1735960.0,...,36408820,19.86750,5559991,30848829,1.19,1.93,Authoritarian,26.2,Salman,King
182,United Arab Emirates,United Arab Emirates,U.A.E. dirham,Abu Dhabi,Western Asia,Asia,Emirati,24.000000,54.000000,3898.0,...,9441129,50.00000,1176081,8265048,1.79,2.76,Authoritarian,29.3,Sheikh Khalifa bin Zayed Al Nahyan,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Palau,Republic of Palau,U.S. dollar,Ngerulmud,Micronesia,Oceania,Palauan,7.500000,134.500000,43.0,...,18055,6.25000,3258,14797,0.00,0.00,Unknown,31.7,Thomas Remengesau Jr.,President
144,São Tomé and Principe,Democratic Republic of São Tomé and Principe,São Tomé and Principe dobra,São Tomé,Middle Africa,Africa,Sao Tomean,1.000000,7.000000,440.0,...,227380,14.54550,55128,172252,0.00,0.00,Unknown,14.6,Evaristo Carvalho,President
143,San Marino,Republic of San Marino,Euro,City of San Marino,Southern Europe,Europe,Sammarinese,43.766667,12.416667,23.0,...,33660,33.33330,763,32897,0.00,0.00,Unknown,42.7,Alessandro Mancini,Captain Regent
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
112,Monaco,Principality of Monaco,Euro,Monaco,Western Europe,Europe,Monegasque,43.733333,7.400000,NaN,...,36469,33.33330,0,36469,0.00,0.00,Unknown,50.5,Albert II,Sovereign Prince

In [135]:
#Find the top 10 countries with the highest forest area.
df=df.sort_values(by="forest_area",ascending=0)
df.iloc[0:10]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
140,Russia,Russian Federation,Russian ruble,Moscow,Eastern Europe,Europe,Russian,60.0,100.0,2154940.0,...,143555736,16.2222,35708054,107847682,1.55,2.94,Authoritarian,35.0,Vladimir Putin,President
22,Brazil,Federative Republic of Brazil,Brazilian real,Brasília,South America,Americas,Brazilian,-10.0,-55.0,2368790.0,...,215313498,17.7388,26795765,188517733,2.38,6.97,Flawed democracy,29.2,Jair Bolsonaro,President
30,Canada,Canada,Canadian dollar,Ottawa,Northern America,Americas,Canadian,60.0,-95.0,577430.0,...,38929902,30.4734,7103929,31825973,4.98,9.15,Full democracy,36.4,Justin Trudeau,Prime Minister
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.0,-97.0,4058100.0,...,333287557,28.7037,56378923,276908634,3.04,7.96,Flawed democracy,33.9,Joe Biden,President
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.0,105.0,5285080.0,...,1412175000,24.9412,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
8,Australia,Commonwealth of Australia,Australian dollar,Canberra,Australia and New Zealand,Oceania,Australian,-27.0,133.0,3557750.0,...,25978935,38.4106,3510274,22468661,4.73,9.09,Full democracy,33.3,Anthony Albanese,Prime Minister
45,Dem. Rep. Congo,Democratic Republic of the Congo,Congolese franc,Kinshasa,Middle Africa,Africa,Congolese,0.0,25.0,335720.0,...,99010212,12.8000,52636799,46373413,1.51,1.49,Authoritarian,11.7,Félix Tshisekedi,President
76,Indonesia,Republic of Indonesia,Indonesian rupiah,Jakarta,South-Eastern Asia,Asia,Indonesian,-5.0,120.0,623000.0,...,275501339,21.9130,115892393,159608946,2.13,6.39,Flawed democracy,25.6,Joko Widodo,President
134,Peru,Republic of Peru,Peruvian new sol,Lima,South America,Americas,Peruvian,-10.0,-76.0,244783.0,...,34049588,40.0000,7249838,26799750,2.59,6.60,Flawed democracy,24.4,Martín Vizcarra,President
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [134]:
#Find the country with the highest health expenditure per capita.
print(df.loc[df['health_expenditure_capita'].idxmax(),'country'])

United States

In [141]:
#Find the average health expenditure by continent.
df.groupby('continent')['health_expenditure_pct_gdp'].mean()

continent
Africa      5.394523
Americas    7.784384
Asia        5.941783
Europe      8.923753
Oceania     9.579200
Name: health_expenditure_pct_gdp, dtype: float64

In [ ]:
# Expert Level
# Find the top 5 countries with the highest GDP per person.

# Hint:

# GDP per capita = gdp / population
# Create a new column called GDP_per_Capita.
# Create a new column called Population_Density.

# Hint:

# Population Density = population / land_area
# Find the country with the highest population density.
# Find the continent with the highest average GDP.
# Find the top 10 countries with both:
# High democracy score
# High life expectancy
# Find countries with:
# Renewable energy consumption > Fossil energy consumption
# Find the country that has:
# Highest life expectancy
# Lowest death rate
# Find the correlation between:
# GDP and Life Expectancy
# GDP and Internet Usage
# Which continent has the highest average internet usage?

In [144]:
# Find the top 5 countries with the highest GDP per person.

# Hint:

# GDP per capita = gdp / population
df["gdp_per_cap"]=df['gdp']/df['population']

In [145]:
df['gdp_per_cap']

140     15606.621250
22       8917.694514
30      54966.488228
184     76398.591742
34      12720.236515
           ...
11      30152.020774
105     33941.006884
119     11913.640669
138     88046.478044
112    235711.426143
Name: gdp_per_cap, Length: 194, dtype: float64

In [148]:
df=df.sort_values(by='gdp_per_cap',ascending=0)
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,gdp_per_cap
112,Monaco,Principality of Monaco,Euro,Monaco,Western Europe,Europe,Monegasque,43.733333,7.400000,NaN,...,33.3333,0,36469,0.00,0.00,Unknown,50.5,Albert II,Sovereign Prince,235711.426143
97,Liechtenstein,Principality of Liechtenstein,Swiss franc,Vaduz,Western Europe,Europe,Liechtensteiner,47.266667,9.533333,53.20,...,28.0000,33610,5717,3.82,0.00,Unknown,39.9,Hereditary Prince Alois,Regent,182735.270933
99,Luxembourg,Grand Duchy of Luxembourg,Euro,Luxembourg,Western Europe,Europe,Luxembourger,49.750000,6.166667,1321.36,...,33.3333,52836,597938,4.99,8.81,Full democracy,35.0,Xavier Bettel,Prime Minister,126426.071109
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.000000,10.000000,9859.62,...,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister,106148.711584
79,Ireland,Ireland,Euro,Dublin,Northern Europe,Europe,Irish,53.000000,-8.000000,45120.00,...,23.1250,1822006,3264982,5.21,9.15,Full democracy,33.9,Leo Varadkar,Taoiseach,104038.971588

In [149]:
# Create a new column called Population_Density.

# Hint:

# Population Density = population / land_area
df['population_density']=df['population']/df['land_area']

In [151]:
df['population_density']

112    17991.613222
97       245.793750
99       252.780777
127       14.980378
79        73.842183
           ...
149      119.225797
31         8.955575
0         63.058692
26       501.930530
44       216.505407
Name: population_density, Length: 194, dtype: float64

In [157]:
# Find the country with the highest population density
print(df.loc[df['population_density'].idxmax()]['country'])

Monaco

In [162]:
# Find the continent with the highest average GDP.
df.groupby('continent')['gdp'].mean()

continent
Africa      5.466804e+10
Americas    9.675583e+11
Asia        7.989775e+11
Europe      5.400586e+11
Oceania     1.402479e+11
Name: gdp, dtype: float64

In [172]:
# Find the top 10 countries with both:
# High democracy score
# High life expectancy

df.sort_values(by=['democracy_score', 'life_expectancy'],ascending=False).head(10)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,gdp_per_cap,population_density
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister,106148.711584,14.980378
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister,72902.854150,3.787563
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister,55873.204588,25.748473
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister,48249.253527,19.460332
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister,66983.147827,147.575925
30,Canada,Canada,Canadian dollar,Ottawa,Northern America,Americas,Canadian,60.0,-95.0,577430.00,...,7103929,31825973,4.98,9.15,Full democracy,36.4,Justin Trudeau,Prime Minister,54966.488228,4.342146
79,Ireland,Ireland,Euro,Dublin,Northern Europe,Europe,Irish,53.0,-8.0,45120.00,...,1822006,3264982,5.21,9.15,Full democracy,33.9,Leo Varadkar,Taoiseach,104038.971588,73.842183
59,Finland,Republic of Finland,Euro,Helsinki,Northern Europe,Europe,Finnish,64.0,26.0,22700.00,...,795690,4761190,9.90,9.14,Full democracy,38.6,Sanna Marin,Prime Minister,50536.632067,18.282819
8,Australia,Commonwealth of Australia,Australian dollar,Canberra,Australia and New Zealand,Oceania,Australian,-27.0,133.0,3557750.00,...,3510274,22468661,4.73,9.09,Full democracy,33.3,Anthony Albanese,Prime Minister,64491.481271,3.377388
165,Switzerland,Switzerland,Swiss franc,Bern,Western Europe,Europe,Swiss,47.0,8.0,15042.10,...,2272064,6497677,7.43,9.03,Full democracy,38.1,Simonetta Sommaruga,President,92101.465710,221.928864

In [173]:
# Find countries with:
# Renewable energy consumption > Fossil energy consumption
df[df['fossil_energy_consumption_pct']<df['renewable_energy_consumption_pct']]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,gdp_per_cap,population_density
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.00,10.0,9859.62,...,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister,106148.711584,14.980378
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.00,-18.0,18720.00,...,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister,72902.854150,3.787563
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.00,15.0,30055.40,...,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister,55873.204588,25.748473
59,Finland,Republic of Finland,Euro,Helsinki,Northern Europe,Europe,Finnish,64.00,26.0,22700.00,...,795690,4761190,9.90,9.14,Full democracy,38.6,Sanna Marin,Prime Minister,50536.632067,18.282819
170,The Bahamas,Commonwealth of The Bahamas,Bahamian dollar,Nassau,Caribbean,Americas,Bahamian,24.25,-76.0,140.00,...,67680,342304,0.00,0.00,Unknown,28.9,Hubert Minnis,Prime Minister,31458.300812,40.957443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Guinea-Bissau,Republic of Guinea-Bissau,West African CFA franc,Bissau,Western Africa,Africa,Guinea-Bissauan,12.00,-15.0,8151.10,...,1157198,948368,2.53,1.98,Authoritarian,14.5,Umaro Sissoco Embaló,President,775.829397,74.877881
45,Dem. Rep. Congo,Democratic Republic of the Congo,Congolese franc,Kinshasa,Middle Africa,Africa,Congolese,0.00,25.0,335720.00,...,52636799,46373413,1.51,1.49,Authoritarian,11.7,Félix Tshisekedi,President,586.464758,43.673590
54,Eritrea,State of Eritrea,Eritrean nakfa,Asmara,Eastern Africa,Africa,Eritrean,15.00,39.0,75920.00,...,2113713,1570319,0.97,2.37,Authoritarian,14.5,Isaias Afwerki,President,560.527162,30.436232
116,Mozambique,Republic of Mozambique,New Mozambican metical,Maputo,Eastern Africa,Africa,Mozambican,-18.25,35.0,414138.00,...,20379448,12590070,2.39,3.85,Authoritarian,13.0,Filipe Nyusi,President,541.454686,41.925682
124,Niger,Republic of Niger,West African CFA franc,Niamey,Western Africa,Africa,Nigerien,16.00,8.0,465970.00,...,21780401,4427576,2.67,3.76,Authoritarian,10.5,Mahamadou Issoufou,President,533.028551,20.689964

In [184]:
# Find the country that has:
# Highest life expectancy
# Lowest death rate
print(df.loc[df['life_expectancy'].idxmax(), 'country'])
print(df.loc[df['death_rate'].idxmin(), 'country'])

Liechtenstein
Qatar

In [190]:
# Find the correlation between:
# GDP and Life Expectancy
# GDP and Internet Usage
df['gdp'].corr(df['life_expectancy'])

np.float64(0.17939616337519823)

In [191]:
df['gdp'].corr(df['internet_pct'])

np.float64(0.13973094660501054)

In [208]:
# Which continent has the highest average internet usage?
print(df.groupby('continent')['internet_pct'].mean().idxmax())

Europe