In [1]:
import pandas as pd
import numpy as ny

In [4]:
df=pd.read_csv('quebec_housing_sales_v2.csv')

In [5]:
df.shape

(5000, 14)

In [6]:
df

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
0,1,Châteauguay,Centre-Ville,Townhouse,3,2,1160,2304.0,2022,NaN,Yes,No,2024,326000
1,2,Trois-Rivières,Cap-de-la-Madeleine,Duplex,4,4,1807,5869.0,2006,2024.0,No,Yes,2025,444000
2,3,Lévis,Charny,Townhouse,3,1,803,3387.0,1989,NaN,Yes,Yes,2025,273000
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
4,5,Longueuil,Greenfield Park,Condo,2,2,714,NaN,1997,2010.0,Yes,No,2022,371000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,Sherbrooke,Lennoxville,Single Family,4,4,1411,9036.0,1985,NaN,Yes,No,2023,406000
4996,4997,Rimouski,Rimouski Centre,Single Family,5,2,1432,6474.0,2010,NaN,Yes,No,2022,198000
4997,4998,Montréal,Villeray,Duplex,4,2,1692,6070.0,1953,NaN,Yes,No,2024,680000
4998,4999,Brossard,Secteur B,Bungalow,2,1,954,4686.0,1994,2013.0,Yes,Yes,2024,431000
4999,5000,Terrebonne,Lachenaie,Condo,1,1,861,NaN,1969,2010.0,Yes,No,2021,472000

In [ ]:
# Easy
# Display the first 10 rows.
# Display the last 5 rows.
# Find the shape of the dataset.
# Display all column names.
# Find the data type of each column.
# Count the number of missing values in each column.
# Count the total number of properties.
# Print only the city, property_type, and sale_price columns.
# Find the average sale price.
# Find the highest sale price.

In [7]:
# Display the first 10 rows.
df.head(10)

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
0,1,Châteauguay,Centre-Ville,Townhouse,3,2,1160,2304.0,2022,NaN,Yes,No,2024,326000
1,2,Trois-Rivières,Cap-de-la-Madeleine,Duplex,4,4,1807,5869.0,2006,2024.0,No,Yes,2025,444000
2,3,Lévis,Charny,Townhouse,3,1,803,3387.0,1989,NaN,Yes,Yes,2025,273000
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
4,5,Longueuil,Greenfield Park,Condo,2,2,714,NaN,1997,2010.0,Yes,No,2022,371000
5,6,Victoriaville,Centre-Ville,Single Family,4,3,2081,5682.0,1967,NaN,Yes,Yes,2023,458000
6,7,Montréal,Outremont,Townhouse,3,3,1036,3343.0,1939,NaN,No,Yes,2023,383000
7,8,Sherbrooke,Lennoxville,Single Family,4,2,1767,4750.0,2007,NaN,Yes,Yes,2023,475000
8,9,Lévis,Saint-Nicolas,Townhouse,4,2,1178,2763.0,1956,2020.0,No,No,2024,337000
9,10,Saint-Jérôme,Bellefeuille,Bungalow,4,1,1063,5380.0,1984,NaN,Yes,Yes,2025,386000

In [8]:
# Display the last 5 rows.
df.tail()

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
4995,4996,Sherbrooke,Lennoxville,Single Family,4,4,1411,9036.0,1985,NaN,Yes,No,2023,406000
4996,4997,Rimouski,Rimouski Centre,Single Family,5,2,1432,6474.0,2010,NaN,Yes,No,2022,198000
4997,4998,Montréal,Villeray,Duplex,4,2,1692,6070.0,1953,NaN,Yes,No,2024,680000
4998,4999,Brossard,Secteur B,Bungalow,2,1,954,4686.0,1994,2013.0,Yes,Yes,2024,431000
4999,5000,Terrebonne,Lachenaie,Condo,1,1,861,NaN,1969,2010.0,Yes,No,2021,472000

In [9]:
# Find the shape of the dataset.
df.shape

(5000, 14)

In [10]:
# Display all column names.
df.columns

Index(['property_id', 'city', 'neighborhood', 'property_type', 'bedrooms',
       'bathrooms', 'living_area_sqft', 'lot_size_sqft', 'year_built',
       'renovation_year', 'garage', 'basement', 'sale_year', 'sale_price'],
      dtype='object')

In [17]:
# Find the data type of each column.
df.dtypes

property_id           int64
city                 object
neighborhood         object
property_type        object
bedrooms              int64
bathrooms             int64
living_area_sqft      int64
lot_size_sqft       float64
year_built            int64
renovation_year     float64
garage               object
basement             object
sale_year             int64
sale_price            int64
dtype: object

In [22]:
# Count the number of missing values in each column.
df.isna().sum()

property_id            0
city                   0
neighborhood           0
property_type          0
bedrooms               0
bathrooms              0
living_area_sqft       0
lot_size_sqft       1211
year_built             0
renovation_year     3408
garage                 0
basement               0
sale_year              0
sale_price             0
dtype: int64

In [32]:
# Count the total number of properties.
df['property_id'].count()

np.int64(5000)

In [43]:
# Print only the city, property_type, and sale_price columns.
df[['property_type','city','property_type','sale_price']]

      property_type            city  property_type  sale_price
0         Townhouse     Châteauguay      Townhouse      326000
1            Duplex  Trois-Rivières         Duplex      444000
2         Townhouse           Lévis      Townhouse      273000
3     Single Family           Laval  Single Family      465000
4             Condo       Longueuil          Condo      371000
...             ...             ...            ...         ...
4995  Single Family      Sherbrooke  Single Family      406000
4996  Single Family        Rimouski  Single Family      198000
4997         Duplex        Montréal         Duplex      680000
4998       Bungalow        Brossard       Bungalow      431000
4999          Condo      Terrebonne          Condo      472000

[5000 rows x 4 columns]

In [45]:
# Find the average sale price.
df['sale_price'].mean()

np.float64(480214.0)

In [48]:
# Find the highest sale price.
df.loc[df['sale_price'].idxmax(),'city']

'Longueuil'

In [ ]:
# Medium
# Find the property with the highest sale price.
# Find the property with the lowest sale price.
# Find all houses with more than 3 bedrooms.
# Find all properties with at least 2 bathrooms.
# Find all properties sold after 2020.
# Find the average living area.
# Find the average lot size.
# Count how many properties are in each city.
# Count how many properties belong to each property type.
# Find the average sale price for each city.

In [49]:
# Find the property with the highest sale price.
df.loc[df['sale_price'].idxmax()]

property_id                    3651
city                      Longueuil
neighborhood        Greenfield Park
property_type               Triplex
bedrooms                          6
bathrooms                         4
living_area_sqft               2327
lot_size_sqft                4428.0
year_built                     2011
renovation_year                 NaN
garage                          Yes
basement                        Yes
sale_year                      2025
sale_price                  1425000
Name: 3650, dtype: object

In [50]:
# Find the property with the lowest sale price.
df.loc[df['sale_price'].idxmin()]

property_id                       2902
city                       Baie-Comeau
neighborhood        Baie-Comeau Centre
property_type                    Condo
bedrooms                             2
bathrooms                            1
living_area_sqft                   638
lot_size_sqft                      NaN
year_built                        1962
renovation_year                    NaN
garage                             Yes
basement                            No
sale_year                         2022
sale_price                      114000
Name: 2901, dtype: object

In [55]:
# Find all houses with more than 3 bedrooms.
df[df['bedrooms']<=3]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
0,1,Châteauguay,Centre-Ville,Townhouse,3,2,1160,2304.0,2022,NaN,Yes,No,2024,326000
2,3,Lévis,Charny,Townhouse,3,1,803,3387.0,1989,NaN,Yes,Yes,2025,273000
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
4,5,Longueuil,Greenfield Park,Condo,2,2,714,NaN,1997,2010.0,Yes,No,2022,371000
6,7,Montréal,Outremont,Townhouse,3,3,1036,3343.0,1939,NaN,No,Yes,2023,383000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988,4989,Saint-Bruno-de-Montarville,Centre-Ville,Single Family,3,4,1291,10207.0,2012,NaN,Yes,Yes,2024,621000
4989,4990,Québec,Vanier,Condo,2,2,586,NaN,2005,NaN,No,No,2024,288000
4992,4993,Montréal,Ahuntsic,Townhouse,3,2,1128,2314.0,1968,2013.0,No,Yes,2023,448000
4998,4999,Brossard,Secteur B,Bungalow,2,1,954,4686.0,1994,2013.0,Yes,Yes,2024,431000
4999,5000,Terrebonne,Lachenaie,Condo,1,1,861,NaN,1969,2010.0,Yes,No,2021,472000

In [56]:
# Find all properties with at least 2 bathrooms.
df[df['bathrooms']>=2]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
0,1,Châteauguay,Centre-Ville,Townhouse,3,2,1160,2304.0,2022,NaN,Yes,No,2024,326000
1,2,Trois-Rivières,Cap-de-la-Madeleine,Duplex,4,4,1807,5869.0,2006,2024.0,No,Yes,2025,444000
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
4,5,Longueuil,Greenfield Park,Condo,2,2,714,NaN,1997,2010.0,Yes,No,2022,371000
5,6,Victoriaville,Centre-Ville,Single Family,4,3,2081,5682.0,1967,NaN,Yes,Yes,2023,458000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,4994,Châteauguay,Centre-Ville,Duplex,4,4,1839,5861.0,1999,2006.0,No,Yes,2022,307000
4994,4995,Repentigny,Le Gardeur,Single Family,6,3,847,10663.0,1994,NaN,Yes,Yes,2023,506000
4995,4996,Sherbrooke,Lennoxville,Single Family,4,4,1411,9036.0,1985,NaN,Yes,No,2023,406000
4996,4997,Rimouski,Rimouski Centre,Single Family,5,2,1432,6474.0,2010,NaN,Yes,No,2022,198000
4997,4998,Montréal,Villeray,Duplex,4,2,1692,6070.0,1953,NaN,Yes,No,2024,680000

In [63]:
# Find all properties sold after 2020.
df[df['sale_year']>2020]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
0,1,Châteauguay,Centre-Ville,Townhouse,3,2,1160,2304.0,2022,NaN,Yes,No,2024,326000
1,2,Trois-Rivières,Cap-de-la-Madeleine,Duplex,4,4,1807,5869.0,2006,2024.0,No,Yes,2025,444000
2,3,Lévis,Charny,Townhouse,3,1,803,3387.0,1989,NaN,Yes,Yes,2025,273000
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
4,5,Longueuil,Greenfield Park,Condo,2,2,714,NaN,1997,2010.0,Yes,No,2022,371000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,Sherbrooke,Lennoxville,Single Family,4,4,1411,9036.0,1985,NaN,Yes,No,2023,406000
4996,4997,Rimouski,Rimouski Centre,Single Family,5,2,1432,6474.0,2010,NaN,Yes,No,2022,198000
4997,4998,Montréal,Villeray,Duplex,4,2,1692,6070.0,1953,NaN,Yes,No,2024,680000
4998,4999,Brossard,Secteur B,Bungalow,2,1,954,4686.0,1994,2013.0,Yes,Yes,2024,431000
4999,5000,Terrebonne,Lachenaie,Condo,1,1,861,NaN,1969,2010.0,Yes,No,2021,472000

In [64]:
# Find the average living area.
df['living_area_sqft'].mean()

np.float64(1313.6938)

In [65]:
# Find the average lot size.
df['lot_size_sqft'].mean()

np.float64(6257.154658221167)

In [79]:
# Count how many properties are in each city.
df.groupby('city')['property_id'].count()

city
Alma                           36
Baie-Comeau                    22
Blainville                    112
Boucherville                   72
Brossard                      244
Candiac                        55
Châteauguay                    81
Dollard-des-Ormeaux            82
Drummondville                  89
Gatineau                      207
Granby                         90
Laval                         460
Longueuil                     394
Lévis                         124
Mirabel                        90
Montréal                      919
Pointe-Claire                  51
Québec                        529
Repentigny                    147
Rimouski                       49
Rouyn-Noranda                  27
Saguenay                       93
Saint-Bruno-de-Montarville     57
Saint-Jean-sur-Richelieu      121
Saint-Jérôme                  117
Sept-Îles                      36
Sherbrooke                    220
Terrebonne                    174
Trois-Rivières                137
Val-d'Or                       30
Vaudreuil-Dorion               79
Victoriaville                  56
Name: property_id, dtype: int64

In [82]:
# Count how many properties belong to each property type.
df.groupby('property_type')['property_type'].count()

property_type
Bungalow          139
Condo            1211
Duplex            493
Single Family    2254
Townhouse         649
Triplex           254
Name: property_type, dtype: int64

In [84]:
# Find the average sale price for each city.
df.groupby('city')['sale_price'].mean()

city
Alma                          264861.111111
Baie-Comeau                   171136.363636
Blainville                    434892.857143
Boucherville                  562833.333333
Brossard                      542938.524590
Candiac                       515090.909091
Châteauguay                   368012.345679
Dollard-des-Ormeaux           580707.317073
Drummondville                 332876.404494
Gatineau                      515371.980676
Granby                        470544.444444
Laval                         576630.434783
Longueuil                     606675.126904
Lévis                         361169.354839
Mirabel                       434000.000000
Montréal                      529662.676823
Pointe-Claire                 599725.490196
Québec                        385296.786389
Repentigny                    575517.006803
Rimouski                      249081.632653
Rouyn-Noranda                 416037.037037
Saguenay                      298698.924731
Saint-Bruno-de-Montarville    560859.649123
Saint-Jean-sur-Richelieu      347842.975207
Saint-Jérôme                  372991.452991
Sept-Îles                     210305.555556
Sherbrooke                    405150.000000
Terrebonne                    612666.666667
Trois-Rivières                340065.693431
Val-d'Or                      250266.666667
Vaudreuil-Dorion              480607.594937
Victoriaville                 419017.857143
Name: sale_price, dtype: float64

In [ ]:
# Find the average sale price for each property type.
# Find the average number of bedrooms in each city.
# Find the average living area for each property type.
# Find the city with the highest average sale price.
# Find the property type with the highest average sale price.
# Find the total number of properties sold in each year.
# Find the average sale price by sale year.
# Find the average lot size by city.
# Find the average bathrooms by property type.
# Find the maximum sale price in each city.

In [85]:
# Find the average sale price for each property type.
df.groupby("property_type")["sale_price"].mean()

property_type
Bungalow         471460.431655
Condo            366817.506193
Duplex           547251.521298
Single Family    524967.613132
Townhouse        359906.009245
Triplex          805787.401575
Name: sale_price, dtype: float64

In [86]:
# Find the average number of bedrooms in each city.
df.groupby("city")["bedrooms"].mean()

city
Alma                          3.694444
Baie-Comeau                   3.090909
Blainville                    3.357143
Boucherville                  3.597222
Brossard                      3.393443
Candiac                       3.581818
Châteauguay                   3.345679
Dollard-des-Ormeaux           3.670732
Drummondville                 3.382022
Gatineau                      3.574879
Granby                        3.500000
Laval                         3.504348
Longueuil                     3.522843
Lévis                         3.443548
Mirabel                       3.500000
Montréal                      3.461371
Pointe-Claire                 3.647059
Québec                        3.529301
Repentigny                    3.319728
Rimouski                      3.612245
Rouyn-Noranda                 3.703704
Saguenay                      3.731183
Saint-Bruno-de-Montarville    3.649123
Saint-Jean-sur-Richelieu      3.396694
Saint-Jérôme                  3.153846
Sept-Îles                     3.444444
Sherbrooke                    3.477273
Terrebonne                    3.517241
Trois-Rivières                3.525547
Val-d'Or                      3.766667
Vaudreuil-Dorion              3.620253
Victoriaville                 3.446429
Name: bedrooms, dtype: float64

In [88]:
# Find the average living area for each property type.
df.groupby("property_type")["living_area_sqft"].mean()

property_type
Bungalow         1025.251799
Condo             751.389761
Duplex           1718.318458
Single Family    1499.908607
Townhouse        1078.032357
Triplex          2316.763780
Name: living_area_sqft, dtype: float64

In [87]:
df.columns

Index(['property_id', 'city', 'neighborhood', 'property_type', 'bedrooms',
       'bathrooms', 'living_area_sqft', 'lot_size_sqft', 'year_built',
       'renovation_year', 'garage', 'basement', 'sale_year', 'sale_price'],
      dtype='object')

In [97]:
# Find the city with the highest average sale price.
df.groupby(["city"])['sale_price'].mean().sort_values(ascending=0).head(1)

city
Terrebonne    612666.666667
Name: sale_price, dtype: float64

In [98]:
# Find the property type with the highest average sale price.
df.groupby(["property_type"])['sale_price'].mean().sort_values(ascending=0).head(1)

property_type
Triplex    805787.401575
Name: sale_price, dtype: float64

In [99]:
# Find the total number of properties sold in each year.
df.groupby(["sale_year"])['property_id'].count()

sale_year
2021     557
2022     816
2023     982
2024    1302
2025    1343
Name: property_id, dtype: int64

In [100]:
# Find the average sale price by sale year.
df.groupby(["sale_year"])['sale_price'].mean()

sale_year
2021    396542.190305
2022    425774.509804
2023    457675.152749
2024    501804.915515
2025    543542.069993
Name: sale_price, dtype: float64

In [102]:
# Find the average lot size by city.
df.groupby(["city"])['lot_size_sqft'].mean()

city
Alma                          5444.133333
Baie-Comeau                   5579.285714
Blainville                    6129.632911
Boucherville                  5666.824561
Brossard                      6031.093923
Candiac                       6039.558140
Châteauguay                   6391.898305
Dollard-des-Ormeaux           6865.092308
Drummondville                 6215.686567
Gatineau                      6038.515924
Granby                        6352.078125
Laval                         6232.836795
Longueuil                     6383.219048
Lévis                         6202.705882
Mirabel                       6126.984848
Montréal                      6270.173601
Pointe-Claire                 5856.000000
Québec                        6276.160891
Repentigny                    6755.064815
Rimouski                      7428.135135
Rouyn-Noranda                 6220.200000
Saguenay                      6483.791667
Saint-Bruno-de-Montarville    6142.214286
Saint-Jean-sur-Richelieu      6841.395604
Saint-Jérôme                  6515.807229
Sept-Îles                     6060.814815
Sherbrooke                    6095.602273
Terrebonne                    6168.014925
Trois-Rivières                6103.425926
Val-d'Or                      6976.592593
Vaudreuil-Dorion              6230.733333
Victoriaville                 5205.906977
Name: lot_size_sqft, dtype: float64

In [103]:
# Find the average bathrooms by property type.
df.groupby(["property_type"])['bathrooms'].mean()

property_type
Bungalow         1.496403
Condo            1.499587
Duplex           2.995943
Single Family    2.532831
Townhouse        1.979969
Triplex          4.464567
Name: bathrooms, dtype: float64

In [104]:
# Find the maximum sale price in each city.
df.groupby(["city"])['sale_price'].max()

city
Alma                           372000
Baie-Comeau                    280000
Blainville                     761000
Boucherville                  1170000
Brossard                      1088000
Candiac                        861000
Châteauguay                    704000
Dollard-des-Ormeaux            973000
Drummondville                  609000
Gatineau                       996000
Granby                        1063000
Laval                         1214000
Longueuil                     1425000
Lévis                          691000
Mirabel                        880000
Montréal                      1417000
Pointe-Claire                 1207000
Québec                         834000
Repentigny                    1090000
Rimouski                       406000
Rouyn-Noranda                  671000
Saguenay                       523000
Saint-Bruno-de-Montarville     935000
Saint-Jean-sur-Richelieu       658000
Saint-Jérôme                   779000
Sept-Îles                      341000
Sherbrooke                     879000
Terrebonne                    1318000
Trois-Rivières                 669000
Val-d'Or                       451000
Vaudreuil-Dorion               953000
Victoriaville                  837000
Name: sale_price, dtype: int64

In [ ]:
# Filtering Practice
# Find properties with:
# More than 4 bedrooms
# At least 3 bathrooms
# Find properties where:
# Garage = Yes
# Basement = Yes
# Find properties with sale price greater than $800,000.
# Find properties built before 1990.
# Find renovated properties (renovation_year is not missing).
# Find properties whose living area is greater than 2500 sqft.
# Find properties with lot size greater than 6000 sqft.
# Find all condos in Montreal (or any city present in your dataset).
# Find properties sold in 2023.
# Find properties costing between $500,000 and $700,000.

In [105]:
df.columns

Index(['property_id', 'city', 'neighborhood', 'property_type', 'bedrooms',
       'bathrooms', 'living_area_sqft', 'lot_size_sqft', 'year_built',
       'renovation_year', 'garage', 'basement', 'sale_year', 'sale_price'],
      dtype='object')

In [110]:
# Find properties with:
# More than 4 bedrooms
# At least 3 bathrooms
df[(df['bedrooms']>4)&(df["bathrooms"]>=3)]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
20,21,Laval,Duvernay,Duplex,5,3,1623,4816.0,1986,NaN,Yes,Yes,2023,648000
22,23,Châteauguay,Centre-Ville,Triplex,6,4,2371,5122.0,1987,NaN,No,Yes,2024,559000
24,25,Montréal,Verdun,Duplex,6,4,1984,5285.0,1955,2023.0,No,Yes,2024,723000
27,28,Gatineau,Hull,Duplex,6,4,1558,7432.0,1969,NaN,Yes,Yes,2025,602000
29,30,Mirabel,Saint-Canut,Single Family,6,3,1537,4684.0,2023,NaN,Yes,Yes,2024,494000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4971,4972,Sept-Îles,Sept-Îles Centre,Triplex,7,4,1947,4122.0,1962,2023.0,Yes,Yes,2025,341000
4973,4974,Baie-Comeau,Baie-Comeau Centre,Single Family,5,3,1434,10247.0,1990,2008.0,Yes,Yes,2025,280000
4974,4975,Montréal,Villeray,Single Family,5,4,1863,4734.0,1916,NaN,No,Yes,2025,858000
4991,4992,Montréal,Ville-Marie,Triplex,6,5,2750,5447.0,2015,NaN,Yes,Yes,2025,1189000
4994,4995,Repentigny,Le Gardeur,Single Family,6,3,847,10663.0,1994,NaN,Yes,Yes,2023,506000

In [112]:
# Find properties where:
# Garage = Yes
# Basement = Yes
df[(df['garage']=='Yes')&(df['basement']=='Yes')][['property_id','city']]

      property_id                        city
2               3                       Lévis
3               4                       Laval
5               6               Victoriaville
7               8                  Sherbrooke
9              10                Saint-Jérôme
...           ...                         ...
4988         4989  Saint-Bruno-de-Montarville
4990         4991                    Montréal
4991         4992                    Montréal
4994         4995                  Repentigny
4998         4999                    Brossard

[2239 rows x 2 columns]

In [113]:
# Find properties with sale price greater than $800,000.
df[df["sale_price"]>800000]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
39,40,Montréal,Lachine,Duplex,5,3,1960,4686.0,2021,NaN,Yes,Yes,2025,927000
54,55,Longueuil,Vieux-Longueuil,Single Family,6,3,1313,10233.0,1998,NaN,No,Yes,2025,853000
65,66,Laval,Fabreville,Triplex,6,4,2669,3109.0,1982,2009.0,Yes,Yes,2023,952000
113,114,Gatineau,Gatineau Centre,Single Family,3,2,1998,10005.0,1979,NaN,Yes,Yes,2025,801000
158,159,Laval,Duvernay,Single Family,6,2,1609,8683.0,1985,2024.0,Yes,Yes,2025,850000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4854,4855,Laval,Chomedey,Triplex,7,3,2279,5480.0,2013,NaN,Yes,Yes,2021,864000
4888,4889,Laval,Vimont,Triplex,8,6,2366,4707.0,1980,2017.0,Yes,Yes,2022,930000
4974,4975,Montréal,Villeray,Single Family,5,4,1863,4734.0,1916,NaN,No,Yes,2025,858000
4981,4982,Terrebonne,Lachenaie,Single Family,3,2,1662,7096.0,2016,2023.0,Yes,Yes,2025,808000
4991,4992,Montréal,Ville-Marie,Triplex,6,5,2750,5447.0,2015,NaN,Yes,Yes,2025,1189000

In [115]:
# Find properties built before 1990.
df[df["year_built"]<1990]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
2,3,Lévis,Charny,Townhouse,3,1,803,3387.0,1989,NaN,Yes,Yes,2025,273000
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
5,6,Victoriaville,Centre-Ville,Single Family,4,3,2081,5682.0,1967,NaN,Yes,Yes,2023,458000
6,7,Montréal,Outremont,Townhouse,3,3,1036,3343.0,1939,NaN,No,Yes,2023,383000
8,9,Lévis,Saint-Nicolas,Townhouse,4,2,1178,2763.0,1956,2020.0,No,No,2024,337000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4987,4988,Châteauguay,Centre-Ville,Single Family,3,3,1375,6852.0,1970,NaN,Yes,Yes,2024,335000
4992,4993,Montréal,Ahuntsic,Townhouse,3,2,1128,2314.0,1968,2013.0,No,Yes,2023,448000
4995,4996,Sherbrooke,Lennoxville,Single Family,4,4,1411,9036.0,1985,NaN,Yes,No,2023,406000
4997,4998,Montréal,Villeray,Duplex,4,2,1692,6070.0,1953,NaN,Yes,No,2024,680000
4999,5000,Terrebonne,Lachenaie,Condo,1,1,861,NaN,1969,2010.0,Yes,No,2021,472000

In [117]:
# Find renovated properties (renovation_year is not missing).
df[df['renovation_year'].notnull()]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
1,2,Trois-Rivières,Cap-de-la-Madeleine,Duplex,4,4,1807,5869.0,2006,2024.0,No,Yes,2025,444000
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
4,5,Longueuil,Greenfield Park,Condo,2,2,714,NaN,1997,2010.0,Yes,No,2022,371000
8,9,Lévis,Saint-Nicolas,Townhouse,4,2,1178,2763.0,1956,2020.0,No,No,2024,337000
19,20,Val-d'Or,Val-d'Or Centre,Single Family,4,4,1259,7170.0,1962,2016.0,Yes,No,2023,284000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4983,4984,Saint-Jean-sur-Richelieu,Centre-Ville,Single Family,4,1,1244,8820.0,1957,2005.0,Yes,Yes,2021,314000
4992,4993,Montréal,Ahuntsic,Townhouse,3,2,1128,2314.0,1968,2013.0,No,Yes,2023,448000
4993,4994,Châteauguay,Centre-Ville,Duplex,4,4,1839,5861.0,1999,2006.0,No,Yes,2022,307000
4998,4999,Brossard,Secteur B,Bungalow,2,1,954,4686.0,1994,2013.0,Yes,Yes,2024,431000
4999,5000,Terrebonne,Lachenaie,Condo,1,1,861,NaN,1969,2010.0,Yes,No,2021,472000

In [120]:
# Find properties whose living area is greater than 2500 sqft.
df[df['living_area_sqft']>2500]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
65,66,Laval,Fabreville,Triplex,6,4,2669,3109.0,1982,2009.0,Yes,Yes,2023,952000
103,104,Boucherville,Boucherville Centre,Triplex,6,3,2603,4126.0,1977,NaN,Yes,No,2022,723000
188,189,Laval,Chomedey,Triplex,6,6,2525,4198.0,1990,NaN,Yes,Yes,2022,936000
221,222,Laval,Chomedey,Triplex,7,4,2630,4599.0,2018,NaN,Yes,Yes,2024,1087000
225,226,Montréal,Lachine,Triplex,5,6,2768,6463.0,1958,NaN,Yes,Yes,2022,865000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4215,4216,Longueuil,Saint-Hubert,Triplex,5,4,2616,3711.0,1955,NaN,Yes,Yes,2025,1186000
4695,4696,Longueuil,Vieux-Longueuil,Triplex,6,4,2531,4376.0,1973,NaN,Yes,Yes,2024,1002000
4746,4747,Sherbrooke,Rock Forest,Triplex,6,4,2590,5894.0,2011,NaN,Yes,Yes,2025,879000
4864,4865,Québec,Beauport,Triplex,6,4,2515,4661.0,1979,NaN,Yes,No,2023,593000
4991,4992,Montréal,Ville-Marie,Triplex,6,5,2750,5447.0,2015,NaN,Yes,Yes,2025,1189000

In [121]:
# Find properties with lot size greater than 6000 sqft.
df[df["lot_size_sqft"]>6000]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
14,15,Mirabel,Sainte-Monique,Single Family,4,2,1450,6792.0,1975,NaN,Yes,No,2024,479000
18,19,Châteauguay,Centre-Ville,Single Family,4,3,1642,6265.0,1964,NaN,Yes,Yes,2021,383000
19,20,Val-d'Or,Val-d'Or Centre,Single Family,4,4,1259,7170.0,1962,2016.0,Yes,No,2023,284000
27,28,Gatineau,Hull,Duplex,6,4,1558,7432.0,1969,NaN,Yes,Yes,2025,602000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990,4991,Montréal,Saint-Léonard,Single Family,4,3,1255,6077.0,2004,NaN,Yes,Yes,2023,554000
4994,4995,Repentigny,Le Gardeur,Single Family,6,3,847,10663.0,1994,NaN,Yes,Yes,2023,506000
4995,4996,Sherbrooke,Lennoxville,Single Family,4,4,1411,9036.0,1985,NaN,Yes,No,2023,406000
4996,4997,Rimouski,Rimouski Centre,Single Family,5,2,1432,6474.0,2010,NaN,Yes,No,2022,198000
4997,4998,Montréal,Villeray,Duplex,4,2,1692,6070.0,1953,NaN,Yes,No,2024,680000

In [130]:
# Find all condos in Montreal (or any city present in your dataset).
df[(df['property_type'] == 'Condo') & (df['city'] == 'Montreal')]

Empty DataFrame
Columns: [property_id, city, neighborhood, property_type, bedrooms, bathrooms, living_area_sqft, lot_size_sqft, year_built, renovation_year, garage, basement, sale_year, sale_price]
Index: []

In [131]:
# Find all condos in Montreal (or any city present in your dataset).
df[df['property_type'] == 'Condo']

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
4,5,Longueuil,Greenfield Park,Condo,2,2,714,NaN,1997,2010.0,Yes,No,2022,371000
10,11,Longueuil,Le Vieux-Longueuil,Condo,1,2,768,NaN,2014,NaN,Yes,No,2025,523000
13,14,Repentigny,Le Gardeur,Condo,1,1,991,NaN,2002,NaN,No,No,2024,534000
15,16,Candiac,Candiac Centre,Condo,2,2,806,NaN,2010,NaN,No,No,2025,464000
16,17,Baie-Comeau,Baie-Comeau Centre,Condo,3,1,512,NaN,1984,NaN,Yes,No,2025,153000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4977,4978,Rimouski,Rimouski Centre,Condo,3,1,829,NaN,2021,NaN,No,No,2023,194000
4984,4985,Laval,Fabreville,Condo,2,2,819,NaN,1971,NaN,Yes,No,2022,386000
4986,4987,Québec,Sainte-Foy,Condo,1,1,745,NaN,1967,NaN,No,No,2023,257000
4989,4990,Québec,Vanier,Condo,2,2,586,NaN,2005,NaN,No,No,2024,288000
4999,5000,Terrebonne,Lachenaie,Condo,1,1,861,NaN,1969,2010.0,Yes,No,2021,472000

In [133]:
# Find properties costing between $500,000 and $700,000.
df[(df['sale_price']>500000)&(df['sale_price']<700000)]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
10,11,Longueuil,Le Vieux-Longueuil,Condo,1,2,768,NaN,2014,NaN,Yes,No,2025,523000
13,14,Repentigny,Le Gardeur,Condo,1,1,991,NaN,2002,NaN,No,No,2024,534000
20,21,Laval,Duvernay,Duplex,5,3,1623,4816.0,1986,NaN,Yes,Yes,2023,648000
22,23,Châteauguay,Centre-Ville,Triplex,6,4,2371,5122.0,1987,NaN,No,Yes,2024,559000
23,24,Montréal,Outremont,Bungalow,3,2,1149,4139.0,1989,NaN,Yes,Yes,2024,586000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4978,4979,Montréal,Ahuntsic,Single Family,3,3,1673,6653.0,1909,NaN,Yes,No,2022,514000
4988,4989,Saint-Bruno-de-Montarville,Centre-Ville,Single Family,3,4,1291,10207.0,2012,NaN,Yes,Yes,2024,621000
4990,4991,Montréal,Saint-Léonard,Single Family,4,3,1255,6077.0,2004,NaN,Yes,Yes,2023,554000
4994,4995,Repentigny,Le Gardeur,Single Family,6,3,847,10663.0,1994,NaN,Yes,Yes,2023,506000
4997,4998,Montréal,Villeray,Duplex,4,2,1692,6070.0,1953,NaN,Yes,No,2024,680000

In [134]:
# Find properties sold in 2023.
df[df['sale_year']==2023]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
5,6,Victoriaville,Centre-Ville,Single Family,4,3,2081,5682.0,1967,NaN,Yes,Yes,2023,458000
6,7,Montréal,Outremont,Townhouse,3,3,1036,3343.0,1939,NaN,No,Yes,2023,383000
7,8,Sherbrooke,Lennoxville,Single Family,4,2,1767,4750.0,2007,NaN,Yes,Yes,2023,475000
17,18,Lévis,Lévis Centre,Condo,2,2,862,NaN,2021,NaN,No,No,2023,299000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4986,4987,Québec,Sainte-Foy,Condo,1,1,745,NaN,1967,NaN,No,No,2023,257000
4990,4991,Montréal,Saint-Léonard,Single Family,4,3,1255,6077.0,2004,NaN,Yes,Yes,2023,554000
4992,4993,Montréal,Ahuntsic,Townhouse,3,2,1128,2314.0,1968,2013.0,No,Yes,2023,448000
4994,4995,Repentigny,Le Gardeur,Single Family,6,3,847,10663.0,1994,NaN,Yes,Yes,2023,506000
4995,4996,Sherbrooke,Lennoxville,Single Family,4,4,1411,9036.0,1985,NaN,Yes,No,2023,406000

In [122]:
df['property_type'].unique()

array(['Townhouse', 'Duplex', 'Single Family', 'Condo', 'Bungalow',
       'Triplex'], dtype=object)

In [ ]:
# Sorting Practice
# Find the top 10 most expensive properties.
# Find the cheapest 10 properties.
# Sort properties by living area.
# Sort by sale price and then by bedrooms.
# Find the oldest property.

In [137]:
# Find the top 10 most expensive properties.
df.sort_values(by="sale_price",ascending=0).head(10)

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
3650,3651,Longueuil,Greenfield Park,Triplex,6,4,2327,4428.0,2011,NaN,Yes,Yes,2025,1425000
2942,2943,Montréal,Hochelaga-Maisonneuve,Triplex,6,4,2545,4929.0,1964,2018.0,No,Yes,2025,1417000
1446,1447,Montréal,Plateau-Mont-Royal,Triplex,7,5,2491,6207.0,2012,2017.0,No,Yes,2025,1413000
354,355,Montréal,Saint-Léonard,Triplex,4,4,2604,6874.0,1978,2008.0,Yes,Yes,2025,1347000
1372,1373,Montréal,Pointe-aux-Trembles,Triplex,5,3,2755,5367.0,2011,NaN,No,No,2025,1342000
1182,1183,Terrebonne,Lachenaie,Triplex,6,4,2860,4041.0,1975,2013.0,Yes,Yes,2025,1318000
4440,4441,Montréal,Villeray,Triplex,6,5,2424,4782.0,1993,NaN,Yes,Yes,2024,1277000
1008,1009,Montréal,Plateau-Mont-Royal,Triplex,5,6,2428,4714.0,1945,2016.0,Yes,Yes,2024,1249000
2496,2497,Terrebonne,Lachenaie,Triplex,8,4,2439,4034.0,1989,NaN,Yes,Yes,2025,1241000
4160,4161,Montréal,Pointe-aux-Trembles,Triplex,6,5,2509,4444.0,1978,NaN,No,Yes,2025,1229000

In [140]:
# Find the cheapest 10 properties.
df.sort_values(by="sale_price",ascending=1).head(1)

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
2901,2902,Baie-Comeau,Baie-Comeau Centre,Condo,2,1,638,NaN,1962,NaN,Yes,No,2022,114000

In [141]:
# Sort properties by living area.
df.sort_values(by="living_area_sqft",ascending=0)

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
335,336,Laval,Duvernay,Triplex,5,4,2967,6456.0,2002,NaN,Yes,Yes,2025,1202000
1057,1058,Montréal,Pointe-aux-Trembles,Triplex,6,5,2912,4130.0,1964,NaN,No,Yes,2025,1200000
2174,2175,Brossard,Secteur B,Triplex,6,6,2898,6563.0,1994,2013.0,Yes,Yes,2025,1088000
2895,2896,Trois-Rivières,Centre-Ville,Triplex,5,6,2892,4905.0,1955,NaN,Yes,Yes,2024,666000
258,259,Dollard-des-Ormeaux,West Island,Triplex,7,4,2874,5285.0,1979,NaN,Yes,Yes,2022,884000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,420,Laval,Chomedey,Condo,2,2,483,NaN,1957,2011.0,Yes,No,2021,321000
303,304,Québec,Lebourgneuf,Condo,2,1,483,NaN,2004,NaN,No,No,2025,270000
295,296,Baie-Comeau,Baie-Comeau Centre,Condo,2,2,477,NaN,1985,2019.0,No,No,2024,138000
3179,3180,Terrebonne,La Plaine,Condo,2,1,470,NaN,1966,NaN,No,No,2022,318000
3062,3063,Terrebonne,La Plaine,Condo,2,2,469,NaN,2001,NaN,No,No,2022,339000

In [148]:
# Sort by sale price and then by bedrooms.
df.sort_values(by=['sale_price','bedrooms'],ascending=True)

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
2901,2902,Baie-Comeau,Baie-Comeau Centre,Condo,2,1,638,NaN,1962,NaN,Yes,No,2022,114000
1478,1479,Sept-Îles,Sept-Îles Centre,Condo,2,2,664,NaN,1962,NaN,No,No,2024,118000
1223,1224,Baie-Comeau,Baie-Comeau Centre,Condo,2,2,612,NaN,2017,NaN,Yes,No,2022,121000
1858,1859,Sept-Îles,Sept-Îles Centre,Condo,1,2,764,NaN,1960,NaN,No,No,2021,124000
2033,2034,Baie-Comeau,Baie-Comeau Centre,Condo,3,1,594,NaN,2002,NaN,No,No,2025,126000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1372,1373,Montréal,Pointe-aux-Trembles,Triplex,5,3,2755,5367.0,2011,NaN,No,No,2025,1342000
354,355,Montréal,Saint-Léonard,Triplex,4,4,2604,6874.0,1978,2008.0,Yes,Yes,2025,1347000
1446,1447,Montréal,Plateau-Mont-Royal,Triplex,7,5,2491,6207.0,2012,2017.0,No,Yes,2025,1413000
2942,2943,Montréal,Hochelaga-Maisonneuve,Triplex,6,4,2545,4929.0,1964,2018.0,No,Yes,2025,1417000
3650,3651,Longueuil,Greenfield Park,Triplex,6,4,2327,4428.0,2011,NaN,Yes,Yes,2025,1425000

In [150]:
# Find the oldest property.
df.loc[df['year_built'].idxmin()]

property_id                   750
city                     Montréal
neighborhood        Saint-Léonard
property_type           Townhouse
bedrooms                        3
bathrooms                       2
living_area_sqft              944
lot_size_sqft              3554.0
year_built                   1900
renovation_year               NaN
garage                        Yes
basement                      Yes
sale_year                    2023
sale_price                 333000
Name: 749, dtype: object

In [ ]:
# Advanced
# Create a new column:
# price_per_sqft = sale_price / living_area_sqft
# Find the property with the highest price per square foot.
# Find the average price per square foot by city.
# Which city has the highest average price per square foot?
# Find the most expensive property in each city.
# Find the newest property in each city.
# Find the average sale price for properties with garages versus those without.
# Compare the average sale price of renovated vs. non-renovated properties.
# Find the city with the largest average living area.
# Find the property type with the highest average number of bedrooms.

In [151]:
# Advanced
# Create a new column:
# price_per_sqft = sale_price / living_area_sqft
df['price_per_sqft']=df['sale_price']/df['living_area_sqft']

In [152]:
df['price_per_sqft']

0       281.034483
1       245.711123
2       339.975093
3       429.362881
4       519.607843
           ...
4995    287.739192
4996    138.268156
4997    401.891253
4998    451.781971
4999    548.199768
Name: price_per_sqft, Length: 5000, dtype: float64

In [153]:
# Find the property with the highest price per square foot.
df.loc[df['price_per_sqft'].idxmax()]

property_id                        894
city                         Longueuil
neighborhood        Le Vieux-Longueuil
property_type                    Condo
bedrooms                             2
bathrooms                            2
living_area_sqft                   620
lot_size_sqft                      NaN
year_built                        1978
renovation_year                 2021.0
garage                             Yes
basement                            No
sale_year                         2025
sale_price                      579000
price_per_sqft              933.870968
Name: 893, dtype: object

In [155]:
# Find the average price per square foot by city.
df.groupby(by='city')['price_per_sqft'].mean()

city
Alma                          190.984762
Baie-Comeau                   165.428076
Blainville                    369.104870
Boucherville                  447.947406
Brossard                      459.753013
Candiac                       405.632372
Châteauguay                   293.869167
Dollard-des-Ormeaux           447.132274
Drummondville                 279.538037
Gatineau                      420.474135
Granby                        394.375487
Laval                         461.523060
Longueuil                     482.773025
Lévis                         306.036915
Mirabel                       357.793158
Montréal                      421.419579
Pointe-Claire                 463.386221
Québec                        306.774791
Repentigny                    485.508047
Rimouski                      203.327342
Rouyn-Noranda                 327.650981
Saguenay                      235.717559
Saint-Bruno-de-Montarville    456.642447
Saint-Jean-sur-Richelieu      290.392617
Saint-Jérôme                  313.157558
Sept-Îles                     167.746533
Sherbrooke                    309.088260
Terrebonne                    488.373402
Trois-Rivières                268.472991
Val-d'Or                      186.045522
Vaudreuil-Dorion              378.810509
Victoriaville                 340.994493
Name: price_per_sqft, dtype: float64

In [160]:
# Which city has the highest average price per square foot?
df.groupby(by='city')['price_per_sqft'].mean().sort_values(ascending=0).head(1)

city
Terrebonne    488.373402
Name: price_per_sqft, dtype: float64

In [163]:
# Find the most expensive property in each city.
df.loc[df.groupby(by="city")['sale_price'].idxmax()]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price,price_per_sqft
2169,2170,Alma,Alma Centre,Single Family,5,2,2042,6055.0,1974,2018.0,No,Yes,2025,372000,182.174339
4973,4974,Baie-Comeau,Baie-Comeau Centre,Single Family,5,3,1434,10247.0,1990,2008.0,Yes,Yes,2025,280000,195.258020
2993,2994,Blainville,Blainville Centre,Triplex,6,6,2313,3380.0,1998,2019.0,Yes,No,2024,761000,329.009944
2460,2461,Boucherville,Boucherville Centre,Triplex,8,5,2349,5751.0,2009,NaN,Yes,No,2025,1170000,498.084291
2174,2175,Brossard,Secteur B,Triplex,6,6,2898,6563.0,1994,2013.0,Yes,Yes,2025,1088000,375.431332
3228,3229,Candiac,Candiac Centre,Triplex,7,4,2454,5790.0,1974,NaN,No,Yes,2024,861000,350.855746
3609,3610,Châteauguay,Centre-Ville,Triplex,6,4,2515,5910.0,2005,NaN,No,Yes,2025,704000,279.920477
191,192,Dollard-des-Ormeaux,West Island,Single Family,4,4,1991,9208.0,2008,NaN,Yes,Yes,2025,973000,488.699146
3053,3054,Drummondville,Saint-Charles,Triplex,4,5,2255,5738.0,2016,NaN,Yes,Yes,2025,609000,270.066519
2723,2724,Gatineau,Hull,Triplex,5,6,2541,3868.0,1958,NaN,Yes,Yes,2025,996000,391.971665
1296,1297,Granby,Centre-Ville,Triplex,7,5,2799,5026.0,1961,NaN,Yes,Yes,2025,1063000,379.778492
3114,3115,Laval,Duvernay,Triplex,6,5,2721,3716.0,2004,NaN,Yes,Yes,2025,1214000,446.159500
3650,3651,Longueuil,Greenfield Park,Triplex,6,4,2327,4428.0,2011,NaN,Yes,Yes,2025,1425000,612.376450
2011,2012,Lévis,Saint-Nicolas,Triplex,7,4,2496,7357.0,2019,NaN,No,No,2024,691000,276.842949
353,354,Mirabel,Saint-Canut,Triplex,7,5,2638,3732.0,2011,NaN,Yes,Yes,2025,880000,333.586050
2942,2943,Montréal,Hochelaga-Maisonneuve,Triplex,6,4,2545,4929.0,1964,2018.0,No,Yes,2025,1417000,556.777996
702,703,Pointe-Claire,West Island,Triplex,8,5,2608,6125.0,1960,2019.0,Yes,Yes,2024,1207000,462.806748
2101,2102,Québec,Lebourgneuf,Triplex,6,6,2704,6301.0,2022,NaN,Yes,Yes,2025,834000,308.431953
4214,4215,Repentigny,Repentigny Centre,Triplex,7,4,2398,5712.0,1968,NaN,Yes,No,2024,1090000,454.545455
4931,4932,Rimouski,Rimouski Centre,Single Family,5,3,1803,8123.0,2009,NaN,Yes,Yes,2025,406000,225.180255
3085,3086,Rouyn-Noranda,Rouyn Centre,Triplex,6,4,2821,5535.0,2002,NaN,Yes,Yes,2023,671000,237.858915
4472,4473,Saguenay,La Baie,Triplex,6,5,2322,3882.0,1985,NaN,Yes,No,2024,523000,225.236865
4131,4132,Saint-Bruno-de-Montarville,Centre-Ville,Triplex,5,5,2185,3976.0,2010,NaN,No,No,2024,935000,427.917620
4850,4851,Saint-Jean-sur-Richelieu,Centre-Ville,Triplex,4,5,1918,3847.0,1956,2016.0,Yes,No,2025,658000,343.065693
1843,1844,Saint-Jérôme,Bellefeuille,Triplex,7,5,2293,7108.0,2010,NaN,Yes,Yes,2025,779000,339.729612
4971,4972,Sept-Îles,Sept-Îles Centre,Triplex,7,4,1947,4122.0,1962,2023.0,Yes,Yes,2025,341000,175.141243
4746,4747,Sherbrooke,Rock Forest,Triplex,6,4,2590,5894.0,2011,NaN,Yes,Yes,2025,879000,339.382239
1182,1183,Terrebonne,Lachenaie,Triplex,6,4,2860,4041.0,1975,2013.0,Yes,Yes,2025,1318000,460.839161
1350,1351,Trois-Rivières,Trois-Rivières-Ouest,Triplex,8,5,2317,6713.0,1993,2018.0,Yes,Yes,2024,669000,288.735434
3935,3936,Val-d'Or,Val-d'Or Centre,Single Family,3,4,1621,11042.0,1981,2010.0,Yes,Yes,2025,451000,278.223319
3845,3846,Vaudreuil-Dorion,Centre-Ville,Triplex,5,5,2622,5766.0,1995,NaN,Yes,Yes,2025,953000,363.463005
1100,1101,Victoriaville,Centre-Ville,Triplex,5,5,2818,5715.0,1995,NaN,Yes,Yes,2025,837000,297.019163

In [165]:
# Find the newest property in each city.
df.loc[df['year_built'].idxmax()]

property_id                     26
city                       Mirabel
neighborhood        Sainte-Monique
property_type               Duplex
bedrooms                         5
bathrooms                        2
living_area_sqft              1612
lot_size_sqft               4032.0
year_built                    2023
renovation_year                NaN
garage                         Yes
basement                        No
sale_year                     2025
sale_price                  589000
price_per_sqft          365.384615
Name: 25, dtype: object

In [170]:
# Find the average sale price for properties with garages versus those without.
df.groupby('garage')['sale_price'].mean()

garage
No     456253.280840
Yes    490719.217491
Name: sale_price, dtype: float64

In [182]:
# Compare the average sale price of renovated vs. non-renovated properties.
avg_renovated = df[df['renovation_year'].notna()]['sale_price'].mean()
avg_not_renovated = df[df['renovation_year'].isna()]['sale_price'].mean()

print("Renovated:", avg_renovated)
print("Not Renovated:", avg_not_renovated)

Renovated: 495913.9447236181
Not Renovated: 472879.9882629108

In [188]:
# Find the city with the largest average living area.
df.groupby(by='city')['living_area_sqft'].mean().sort_values(ascending=0).head(1)

city
Alma    1458.611111
Name: living_area_sqft, dtype: float64

In [191]:
# Find the property type with the highest average number of bedrooms.
df.groupby(by='property_type')['bedrooms'].mean().sort_values(ascending=0).head(1)

property_type
Triplex    6.047244
Name: bedrooms, dtype: float64

In [ ]:
# Challenge Questions
# Find the top 5 cities with the highest average property prices.
# Find the top 10 largest houses by living area.
# Find properties that have:
# Garage = Yes
# Basement = Yes
# More than 4 bedrooms
# Sale price under the dataset's average sale price.
# Rank cities by average sale price.
# Find the most expensive property type in each city.

In [198]:
# Find the top 5 cities with the highestp average property prices.
df.groupby(by='city')['sale_price'].mean().sort_values(ascending=0).head(5)

city
Terrebonne             612666.666667
Longueuil              606675.126904
Pointe-Claire          599725.490196
Dollard-des-Ormeaux    580707.317073
Laval                  576630.434783
Name: sale_price, dtype: float64

In [200]:
# Find the top 10 largest houses by living area.
df.sort_values(by='living_area_sqft',ascending=0).head(10)

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price,price_per_sqft
335,336,Laval,Duvernay,Triplex,5,4,2967,6456.0,2002,NaN,Yes,Yes,2025,1202000,405.123020
1057,1058,Montréal,Pointe-aux-Trembles,Triplex,6,5,2912,4130.0,1964,NaN,No,Yes,2025,1200000,412.087912
2174,2175,Brossard,Secteur B,Triplex,6,6,2898,6563.0,1994,2013.0,Yes,Yes,2025,1088000,375.431332
2895,2896,Trois-Rivières,Centre-Ville,Triplex,5,6,2892,4905.0,1955,NaN,Yes,Yes,2024,666000,230.290456
258,259,Dollard-des-Ormeaux,West Island,Triplex,7,4,2874,5285.0,1979,NaN,Yes,Yes,2022,884000,307.585247
1182,1183,Terrebonne,Lachenaie,Triplex,6,4,2860,4041.0,1975,2013.0,Yes,Yes,2025,1318000,460.839161
3644,3645,Châteauguay,Centre-Ville,Triplex,4,4,2848,4697.0,1976,2013.0,Yes,Yes,2024,630000,221.207865
704,705,Candiac,Candiac Centre,Triplex,7,4,2831,3954.0,2010,NaN,No,Yes,2022,736000,259.978806
3085,3086,Rouyn-Noranda,Rouyn Centre,Triplex,6,4,2821,5535.0,2002,NaN,Yes,Yes,2023,671000,237.858915
1100,1101,Victoriaville,Centre-Ville,Triplex,5,5,2818,5715.0,1995,NaN,Yes,Yes,2025,837000,297.019163

In [202]:
# Find properties that have:
# Garage = Yes
# Basement = Yes
# More than 4 bedrooms
# Sale price under the dataset's average sale price.
avg_price=df['sale_price'].mean()
df[(df['garage']=='Yes')&(df['basement']=='Yes')&(df['bedrooms']>4)&(df['sale_price']<avg_price)]

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price,price_per_sqft
91,92,Trois-Rivières,Trois-Rivières-Ouest,Single Family,5,3,1526,9835.0,1967,NaN,Yes,Yes,2025,377000,247.051114
110,111,Québec,Val-Bélair,Single Family,5,2,1554,4824.0,1928,NaN,Yes,Yes,2025,387000,249.034749
130,131,Saguenay,Jonquière,Single Family,6,3,1447,4424.0,2008,NaN,Yes,Yes,2024,365000,252.246026
151,152,Sherbrooke,Lennoxville,Single Family,5,4,1518,7016.0,1963,NaN,Yes,Yes,2023,421000,277.338603
156,157,Longueuil,Saint-Hubert,Single Family,6,1,1431,6673.0,1956,NaN,Yes,Yes,2021,445000,310.971349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4932,4933,Rouyn-Noranda,Rouyn Centre,Single Family,5,2,1850,5021.0,1981,NaN,Yes,Yes,2025,423000,228.648649
4946,4947,Saguenay,Jonquière,Single Family,6,1,1421,8977.0,2020,NaN,Yes,Yes,2021,280000,197.044335
4963,4964,Québec,Lebourgneuf,Single Family,5,3,1420,12485.0,1992,NaN,Yes,Yes,2023,402000,283.098592
4971,4972,Sept-Îles,Sept-Îles Centre,Triplex,7,4,1947,4122.0,1962,2023.0,Yes,Yes,2025,341000,175.141243
4973,4974,Baie-Comeau,Baie-Comeau Centre,Single Family,5,3,1434,10247.0,1990,2008.0,Yes,Yes,2025,280000,195.258020

In [203]:
# Rank cities by average sale price.
df.groupby('city')['sale_price'].mean().sort_values(ascending=0)

city
Terrebonne                    612666.666667
Longueuil                     606675.126904
Pointe-Claire                 599725.490196
Dollard-des-Ormeaux           580707.317073
Laval                         576630.434783
Repentigny                    575517.006803
Boucherville                  562833.333333
Saint-Bruno-de-Montarville    560859.649123
Brossard                      542938.524590
Montréal                      529662.676823
Gatineau                      515371.980676
Candiac                       515090.909091
Vaudreuil-Dorion              480607.594937
Granby                        470544.444444
Blainville                    434892.857143
Mirabel                       434000.000000
Victoriaville                 419017.857143
Rouyn-Noranda                 416037.037037
Sherbrooke                    405150.000000
Québec                        385296.786389
Saint-Jérôme                  372991.452991
Châteauguay                   368012.345679
Lévis                         361169.354839
Saint-Jean-sur-Richelieu      347842.975207
Trois-Rivières                340065.693431
Drummondville                 332876.404494
Saguenay                      298698.924731
Alma                          264861.111111
Val-d'Or                      250266.666667
Rimouski                      249081.632653
Sept-Îles                     210305.555556
Baie-Comeau                   171136.363636
Name: sale_price, dtype: float64